#!/usr/bin/env python3
"""
Test the full flow: chart creation -> embedding -> extraction
Simulates what happens when query_genie returns a response
"""

import sys
import os
import json
import re

# Add parent directory to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Import the chart creation function
import importlib.util
spec = importlib.util.spec_from_file_location(
    "agent_dev", 
    os.path.join(os.path.dirname(os.path.dirname(__file__)), "scripts", "02_agent_development_local.py")
)
agent_dev = importlib.util.module_from_spec(spec)
spec.loader.exec_module(agent_dev)
create_plotly_chart = agent_dev.create_plotly_chart

print("=" * 80)
print("Testing Full Flow: Chart Creation -> Embedding -> Extraction")
print("=" * 80)

# Step 1: Create chart (like query_genie does)
query_data = [
    ['2011-01-26', '-709.5656379102695'],
    ['2011-11-22', '-129.73351960452032'],
    ['2012-09-17', '216.0369243251566'],
    ['2013-07-14', '340.80696277561196'],
    ['2014-05-10', '26.46256108629221'],
]
columns = ['revenue_date', 'max_hourly_revenue']
question = "What is the highest hourly revenue for GANNBG1 by day?"

print("\nStep 1: Creating chart...")
chart_data = create_plotly_chart(query_data, columns, question)

if not chart_data:
    print("✗ Chart creation failed!")
    sys.exit(1)

print(f"✓ Chart created: {chart_data['type']}")
print(f"  JSON type: {type(chart_data['json'])}")
print(f"  JSON keys: {list(chart_data['json'].keys()) if isinstance(chart_data['json'], dict) else 'N/A'}")

# Step 2: Embed in response (like query_genie does)
print("\nStep 2: Embedding chart in response...")
response_parts = []
response_parts.append("The highest hourly revenue for GANNBG1 by day has been retrieved.")
response_parts.append("\n**Raw Query Results:**\n```\n" + "\n".join([str(row) for row in query_data[:5]]) + "\n```\n")

# Embed chart marker
chart_marker = f"\n\n[PLOTLY_CHART_START]\n{json.dumps(chart_data)}\n[PLOTLY_CHART_END]\n"
response_parts.append(chart_marker)

response = "\n".join(response_parts)
response += "\n\n---\n*Note: This answer and SQL were dynamically generated by Databricks Genie.*"

print(f"✓ Response created: {len(response)} characters")
print(f"  Contains PLOTLY_CHART_START: {'PLOTLY_CHART_START' in response}")
print(f"  Chart marker length: {len(chart_marker)}")

# Step 3: Extract charts (like Streamlit does)
print("\nStep 3: Extracting charts from response...")

def extract_plotly_charts(response_text):
    """Extract Plotly chart JSON from response text"""
    charts = []
    
    # Find all chart markers
    pattern = r'\[PLOTLY_CHART_START\]\s*(.*?)\s*\[PLOTLY_CHART_END\]'
    matches = re.findall(pattern, response_text, re.DOTALL | re.MULTILINE)
    
    print(f"  Regex found {len(matches)} chart marker(s)")
    
    for idx, match in enumerate(matches):
        try:
            match_clean = match.strip()
            chart_data = json.loads(match_clean)
            
            # Handle json field
            if isinstance(chart_data, dict) and 'json' in chart_data:
                if isinstance(chart_data['json'], dict):
                    print(f"  ✓ Chart {idx + 1} JSON field is dict (expected)")
                elif isinstance(chart_data['json'], str):
                    print(f"  ⚠️ Chart {idx + 1} JSON field is string (backward compatibility)")
                    chart_data['json'] = json.loads(chart_data['json'])
            
            charts.append(chart_data)
            print(f"  ✓ Chart {idx + 1} parsed successfully")
        except json.JSONDecodeError as e:
            print(f"  ✗ Could not parse chart {idx + 1}: {e}")
            print(f"    Match preview: {match[:200]}")
    
    return charts

charts = extract_plotly_charts(response)

# Step 4: Render chart (like Streamlit does)
print("\nStep 4: Rendering chart...")

if charts:
    for idx, chart_data in enumerate(charts):
        try:
            import plotly.graph_objects as go
            
            chart_json = chart_data.get('json')
            
            if isinstance(chart_json, dict):
                fig = go.Figure(chart_json)
            elif isinstance(chart_json, str):
                chart_dict = json.loads(chart_json)
                fig = go.Figure(chart_dict)
            else:
                raise ValueError(f"Chart JSON is neither string nor dict: {type(chart_json)}")
            
            print(f"✓ Chart {idx + 1} figure created successfully")
            
            # Save as HTML
            html_file = f"/tmp/full_flow_test_{idx + 1}.html"
            fig.write_html(html_file)
            print(f"✓ Chart saved as HTML: {html_file}")
            print(f"  Open in browser: file://{html_file}")
            
        except Exception as e:
            print(f"✗ Failed to render chart {idx + 1}: {e}")
            import traceback
            traceback.print_exc()
else:
    print("✗ No charts extracted")

# Step 5: Show the actual response text around the marker
print("\nStep 5: Response text around chart marker:")
marker_start = response.find('[PLOTLY_CHART_START]')
if marker_start > 0:
    start = max(0, marker_start - 100)
    end = min(len(response), marker_start + 500)
    print(f"  Position: {marker_start}")
    print(f"  Context:\n{response[start:end]}...")
else:
    print("  ✗ Chart marker not found in response!")

print("\n" + "=" * 80)
print("Test Complete")
print("=" * 80)

