#!/usr/bin/env python3
"""
Test script to debug chart extraction locally
Simulates what Streamlit does when extracting charts from agent responses
"""

import sys
import os
import json
import re

# Add parent directory to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Import the chart creation function
import importlib.util
spec = importlib.util.spec_from_file_location(
    "agent_dev", 
    os.path.join(os.path.dirname(os.path.dirname(__file__)), "scripts", "02_agent_development_local.py")
)
agent_dev = importlib.util.module_from_spec(spec)
spec.loader.exec_module(agent_dev)
create_plotly_chart = agent_dev.create_plotly_chart

# Sample response text that simulates what the agent returns
# This includes the chart marker AFTER a code block (the problematic case)
sample_response = """
The highest hourly revenue for GANNBG1 by day has been retrieved. The data shows significant variability.

**Raw Query Results:**
```
['2011-01-26', '-709.5656379102695']
['2011-11-22', '-129.73351960452032']
['2012-09-17', '216.0369243251566']
['2013-07-14', '340.80696277561196']
['2014-05-10', '26.46256108629221']
```

[PLOTLY_CHART_START]
{"type": "line", "json": {"data": [{"x": [0, 1, 2, 3, 4], "y": [-709.57, -129.73, 216.04, 340.81, 26.46], "type": "scatter", "mode": "lines+markers", "name": "", "hovertemplate": "index=%{x}<br>col_1=%{y}<extra></extra>", "showlegend": false, "legendgroup": "", "orientation": "v"}], "layout": {"title": {"text": "Col 1 trend"}}}, "title": "Col 1 trend"}
[PLOTLY_CHART_END]

---

*Note: This answer and SQL were dynamically generated by Databricks Genie.*
"""

print("=" * 80)
print("Testing Chart Extraction")
print("=" * 80)
print(f"\nSample response length: {len(sample_response)} characters")
print(f"Contains PLOTLY_CHART_START: {'PLOTLY_CHART_START' in sample_response}")

# Test extraction function (simulating Streamlit's extract_plotly_charts)
def extract_plotly_charts(response_text):
    """Extract Plotly chart JSON from response text"""
    charts = []
    
    # Find all chart markers - be more flexible with whitespace and code blocks
    # Handle cases where markers might be after code block closers (```)
    pattern = r'(?:```[^\n]*\n)?\[PLOTLY_CHART_START\]\s*(.*?)\s*\[PLOTLY_CHART_END\](?:[^\n]*\n```)?'
    matches = re.findall(pattern, response_text, re.DOTALL | re.MULTILINE)
    
    print(f"\n🔍 Regex found {len(matches)} chart marker(s)")
    
    # Also try simpler pattern
    simple_pattern = r'\[PLOTLY_CHART_START\]\s*(.*?)\s*\[PLOTLY_CHART_END\]'
    simple_matches = re.findall(simple_pattern, response_text, re.DOTALL)
    print(f"🔍 Simple regex found {len(simple_matches)} chart marker(s)")
    
    # Use simple matches for now
    matches = simple_matches
    
    for idx, match in enumerate(matches):
        try:
            # Clean up the match
            match_clean = match.strip()
            
            print(f"\n📦 Chart {idx + 1} match length: {len(match_clean)} characters")
            print(f"   First 200 chars: {match_clean[:200]}")
            
            # Parse the chart data
            chart_data = json.loads(match_clean)
            
            # The 'json' field should now be a dict, not a string (after our fix)
            if isinstance(chart_data, dict) and 'json' in chart_data:
                if isinstance(chart_data['json'], str):
                    # Backward compatibility: if it's still a string, parse it
                    try:
                        inner_json = json.loads(chart_data['json'])
                        chart_data['json'] = inner_json
                        print(f"   ✓ Parsed nested JSON string (backward compatibility)")
                    except json.JSONDecodeError as e:
                        print(f"   ✗ Failed to parse nested JSON: {e}")
                        return charts
                elif isinstance(chart_data['json'], dict):
                    print(f"   ✓ JSON field is already a dict (expected)")
                else:
                    print(f"   ⚠️ JSON field is unexpected type: {type(chart_data['json'])}")
            
            charts.append(chart_data)
            print(f"   ✓ Chart {idx + 1} parsed successfully")
            print(f"   Chart type: {chart_data.get('type')}")
            print(f"   Chart title: {chart_data.get('title')}")
            print(f"   JSON type: {type(chart_data.get('json'))}")
            
        except json.JSONDecodeError as e:
            print(f"   ✗ Could not parse chart data {idx + 1}: {e}")
            print(f"   Match preview: {match[:500]}")
            json_start = match.find('{')
            if json_start > 0:
                print(f"   JSON starts at position {json_start}")
    
    return charts

print("\n" + "=" * 80)
print("Extracting Charts...")
print("=" * 80)

charts = extract_plotly_charts(sample_response)

if charts:
    print(f"\n✓ Successfully extracted {len(charts)} chart(s)")
    
    # Test rendering
    print("\n" + "=" * 80)
    print("Testing Chart Rendering...")
    print("=" * 80)
    
    for idx, chart_data in enumerate(charts):
        try:
            import plotly.graph_objects as go
            
            chart_json = chart_data.get('json')
            
            if isinstance(chart_json, str):
                chart_dict = json.loads(chart_json)
                fig = go.Figure(chart_dict)
            elif isinstance(chart_json, dict):
                fig = go.Figure(chart_json)
            else:
                raise ValueError(f"Chart JSON is neither string nor dict: {type(chart_json)}")
            
            print(f"✓ Chart {idx + 1} figure created successfully")
            
            # Save as HTML
            html_file = f"/tmp/chart_extraction_test_{idx + 1}.html"
            fig.write_html(html_file)
            print(f"✓ Chart saved as HTML: {html_file}")
            print(f"  Open in browser: file://{html_file}")
            
        except Exception as e:
            print(f"✗ Failed to render chart {idx + 1}: {e}")
            import traceback
            traceback.print_exc()
else:
    print("\n✗ No charts extracted")
    print("\nDebugging regex...")
    
    # Show where markers are
    marker_positions = []
    for match_obj in re.finditer(r'\[PLOTLY_CHART_START\]', sample_response):
        marker_positions.append(match_obj.start())
        print(f"  Marker found at position: {match_obj.start()}")
        # Show context around marker
        start = max(0, match_obj.start() - 50)
        end = min(len(sample_response), match_obj.end() + 200)
        print(f"  Context: ...{sample_response[start:end]}...")

print("\n" + "=" * 80)
print("Test Complete")
print("=" * 80)

